# Generated by Django 4.1.1 on 2022-09-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Course description')),
                ('order', models.IntegerField(default=1, verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='TGAdmin',
            fields=[
                ('tg_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('tg_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panel.course', verbose_name='Course')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panel.user', verbose_name='Recording')),
            ],
        ),
    ]
