# Generated by Django 4.1.1 on 2022-09-20 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('who', models.CharField(max_length=200, verbose_name='Преподаватели')),
                ('where', models.CharField(max_length=200, verbose_name='Место')),
                ('day', models.CharField(max_length=200, verbose_name='День недели')),
                ('when', models.CharField(max_length=200, verbose_name='Время')),
                ('order', models.IntegerField(default=1, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='TGAdmin',
            fields=[
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'TGAdmin',
                'verbose_name_plural': 'TGAdmins',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('group_id', models.CharField(blank=True, max_length=100, verbose_name='Номер группы')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panel.message', verbose_name='Сообщение')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panel.user', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Запланированная отправка',
                'verbose_name_plural': 'Запланированные отправки',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panel.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panel.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заяка на курс',
                'verbose_name_plural': 'Заявки на курсы',
            },
        ),
    ]
