# Generated by Django 4.1.1 on 2022-09-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgadmin',
            name='tg_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram ID'),
        ),
    ]
