# Generated by Django 4.1.1 on 2022-09-20 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='when',
            new_name='time',
        ),
    ]
