# Generated by Django 4.1.1 on 2022-09-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_rename_when_course_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img_path',
            field=models.CharField(blank=True, max_length=200, verbose_name='Картинка'),
        ),
    ]
