# Generated by Django 4.2.4 on 2023-09-02 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_course_img_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panel.course', verbose_name='Группа получателей')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panel.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Запланированная отправка 2',
                'verbose_name_plural': 'Запланированные отправки 2',
            },
        ),
    ]
