# Generated by Django 4.1.1 on 2022-09-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_application_message_scheduledmessage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledmessage',
            options={'verbose_name': 'Запланированная отправка', 'verbose_name_plural': 'Запланированные отправки'},
        ),
    ]
