# Generated by Django 4.1.1 on 2022-09-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_scheduledmessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заяка на курс', 'verbose_name_plural': 'Заявки на курсы'},
        ),
    ]
