# Generated by Django 4.2.4 on 2023-09-02 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_scheduledmessage2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduledMessage2',
            new_name='GroupedScheduledMessage',
        ),
        migrations.AlterModelOptions(
            name='groupedscheduledmessage',
            options={'verbose_name': 'Запланированная групповая отправка', 'verbose_name_plural': 'Запланированные групповые отправки'},
        ),
    ]
