# Generated by Django 4.1.1 on 2022-09-19 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_application_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='recording',
            new_name='user',
        ),
    ]
